export default {
  'wave-shadow-color': 'transparent',
  block: '#ffffff',
  'base-bg': '#ffffff', //背景
  'bg-hover': 'rgba(46,50,56,0.05)',
  'border-color': 'rgb(224, 224, 230)',
  'item-bg-hover': '#f2f5fc',
  'overlay-dart': '#464d6e',
  'overlay-text': '#dfe1e6',
  line: '#aea6ad', //边框
  shadow: 'rgba(37, 43, 58, 0.2)',
  'brand-shadow': 'rgb(124, 145, 229, 0.3)',
  'danger-shadow': 'rgba(208, 48, 80, 0.2)',
  brand: '#5e7ce0',
  'brand-hover': '#7693f5',
  'brand-active': '#344899',
  'brand-bg': '#f2f5fc',
  danger: '#f66f6a',
  'danger-active': '#b12220',
  'danger-bg': '#ffeeed',
  warning: '#fac20a',
  'warning-active': '#cf9236',
  'warning-bg': '#fff3e8',
  success: '#50d4ab',
  'success-active': '#449c81',
  'success-bg': '#edfff9',
  info: '#909399',
  'info-active': '#82848a',
  'info-bg': '#f2f5fc',
  text: '#2f272f',
  waiting: '#9faad7',
  'text-weak': '#575d6c',
  'light-text': '#ffffff',
  'title-text': 'rgb(31, 34, 37)',
  'disabled-bg': '#f6f6f6',
  'disabled-line': '#dfe1e6',
  'disabled-text': '#cbcacb',
  placeholder: '#babbc0',
  'font-size': '12px',
  'font-size-card-title': '14px',
  'font-size-page-title': '16px',
  'font-size-modal-title': '18px',
  'font-size-price': '20px',
  'font-size-data-overview': '24px',
  'font-size-icon': '16px',
  'font-size-sm': '12px',
  'font-size-md': '14px',
  'font-size-lg': '15px',
  'font-title-weight': 'bold',
  'font-content-weight': 'normal',
  'line-height-base': '1.5',
  'border-radius': '4px',
  'border-radius-feedback': '4px',
  'border-radius-card': '6px',
  'scrollbar-color': 'rgba(0, 0, 0, 0.25)',
  'scrollbar-color-hover': 'rgba(0, 0, 0, 0.4)'
}
