# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Yarn Setup
        # You may pin to the exact commit or the version.
        # uses: DerYeger/yarn-setup-action@f55be5383ea94f5eb25b20aee609af4603a68dde
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          # The version of Node.js that will be used
          node-version: "16.X"
      - name: install deps
        run: yarn install
      - name: build cli
        run: yarn cli:build
      - name: build docs
        run: yarn cli build
      - name: GitHub Pages v3
        # You may pin to the exact commit or the version.
        # uses: peaceiris/actions-github-pages@b80a30e9bf3c1ec596532c3813f0aff094f555e2
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          publish_dir: /docs/.vitepress/dist
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
